### PR TITLE
Erica22

### PR DESCRIPTION
**Pull request by ynfanteerica**

### CODE REVIEW

**Review by ErGent — COMMENTED** [review]
I think "Layout down the Middle" is relevant to the layout of the task addition div, this one looks good. @IsisRobbs

**Review by ErGent — COMMENTED** [review]
I think "changes" is giving the 2 divs space between, also looks good.

**Review by ErGent — APPROVED** [review]
Removed JWD folder because it looked like the remnant of a nested git repository. All the rest looks great!

**Comment by IsisRobbs** [comment]
All the changes look great. I will go ahead and merge

**Pull request merged**
